//! `codex app-server`: one long-lived process speaking JSON-RPC (one object per line, no
//! `jsonrpc` field) that streams `item/agentMessage/delta` as the reply is written. The
//! protocol is generated by `codex app-server generate-ts`; only the few calls below are used.

use std::path::Path;
use std::process::Stdio;

use serde_json::{Value, json};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader, Lines};
use tokio::process::{Child, ChildStdin, ChildStdout, Command};
use tokio::sync::mpsc;

use crate::{Delta, PERSONA, Turn, is_image, prompt};

#[derive(Debug)]
pub(crate) struct AppServer {
    _child: Child,
    stdin: ChildStdin,
    lines: Lines<BufReader<ChildStdout>>,
    next_id: u64,
    pub(crate) thread: String,
}

/// What a message from the server means for the turn being read.
#[derive(Debug, PartialEq)]
pub(crate) enum Msg {
    Response {
        id: u64,
        result: Value,
    },
    Failure {
        id: u64,
        message: String,
    },
    /// The server asks us something (an approval…): answered with an error, never a yes.
    Request {
        id: Value,
    },
    Delta(String),
    TurnDone {
        error: Option<String>,
    },
    Error(String),
    Other,
}

pub(crate) fn classify(raw: &str) -> Msg {
    let Ok(v) = serde_json::from_str::<Value>(raw) else {
        return Msg::Other;
    };
    let method = v.get("method").and_then(Value::as_str);
    match (v.get("id"), method) {
        (Some(id), Some(_)) => Msg::Request { id: id.clone() },
        (Some(id), None) => {
            let id = id.as_u64().unwrap_or(0);
            match v.get("error") {
                Some(e) => Msg::Failure {
                    id,
                    message: e["message"].as_str().unwrap_or("request failed").to_string(),
                },
                None => Msg::Response {
                    id,
                    result: v["result"].clone(),
                },
            }
        }
        (None, Some("item/agentMessage/delta")) => v["params"]["delta"]
            .as_str()
            .map_or(Msg::Other, |d| Msg::Delta(d.to_string())),
        (None, Some("turn/completed")) => {
            let turn = &v["params"]["turn"];
            let failed = turn["status"].as_str().is_some_and(|s| s == "failed");
            Msg::TurnDone {
                error: failed.then(|| {
                    turn["error"]["message"]
                        .as_str()
                        .unwrap_or("the turn failed")
                        .to_string()
                }),
            }
        }
        (None, Some("error")) if v["params"]["willRetry"] != true => Msg::Error(
            v["params"]["error"]["message"]
                .as_str()
                .unwrap_or("error")
                .to_string(),
        ),
        _ => Msg::Other,
    }
}

impl AppServer {
    /// Starts the server and opens (or reopens) the conversation.
    pub(crate) async fn start(work_dir: &Path, resume: Option<&str>) -> Result<Self, String> {
        let mut child = Command::new("codex")
            // No user hooks: the chat must never show up on the island as a session.
            .args(["app-server", "-c", "features.hooks=false"])
            .current_dir(work_dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .kill_on_drop(true)
            .spawn()
            .map_err(|e| e.to_string())?;
        let stdin = child.stdin.take().ok_or("no stdin")?;
        let stdout = child.stdout.take().ok_or("no stdout")?;
        let mut server = Self {
            _child: child,
            stdin,
            lines: BufReader::new(stdout).lines(),
            next_id: 1,
            thread: String::new(),
        };

        server
            .call("initialize", json!({ "clientInfo": { "name": "vultures-ai", "title": "Vultures AI", "version": env!("CARGO_PKG_VERSION") }, "capabilities": null }))
            .await?;
        server.write(&json!({ "method": "initialized" })).await?;

        let common = json!({
            "cwd": work_dir,
            "approvalPolicy": "never",
            "sandbox": "read-only",
            "developerInstructions": PERSONA,
        });
        let result = match resume {
            Some(id) => {
                let mut params = common.clone();
                params["threadId"] = json!(id);
                server.call("thread/resume", params).await?
            }
            None => server.call("thread/start", common).await?,
        };
        server.thread = result["thread"]["id"].as_str().ok_or("no thread id")?.to_string();
        Ok(server)
    }

    /// One turn, streaming the reply.
    pub(crate) async fn turn(&mut self, turn: &Turn, out: &mpsc::Sender<Delta>) -> Result<(), String> {
        let mut input =
            vec![json!({ "type": "text", "text": prompt(turn, false, false), "text_elements": [] })];
        for image in turn.files.iter().filter(|f| is_image(f)) {
            input.push(json!({ "type": "localImage", "path": image }));
        }
        let id = self
            .send("turn/start", json!({ "threadId": self.thread, "input": input }))
            .await?;
        loop {
            match self.read().await? {
                Msg::Delta(text) => {
                    let _ = out.send(Delta::Text { text }).await;
                }
                Msg::TurnDone { error: None } => return Ok(()),
                Msg::TurnDone { error: Some(e) } | Msg::Error(e) => return Err(e),
                Msg::Failure { id: got, message } if got == id => return Err(message),
                _ => {}
            }
        }
    }

    async fn call(&mut self, method: &str, params: Value) -> Result<Value, String> {
        let id = self.send(method, params).await?;
        loop {
            match self.read().await? {
                Msg::Response { id: got, result } if got == id => return Ok(result),
                Msg::Failure { id: got, message } if got == id => return Err(message),
                _ => {}
            }
        }
    }

    async fn send(&mut self, method: &str, params: Value) -> Result<u64, String> {
        let id = self.next_id;
        self.next_id += 1;
        self.write(&json!({ "id": id, "method": method, "params": params }))
            .await?;
        Ok(id)
    }

    async fn write(&mut self, msg: &Value) -> Result<(), String> {
        let mut line = msg.to_string();
        line.push('\n');
        self.stdin
            .write_all(line.as_bytes())
            .await
            .map_err(|e| e.to_string())?;
        self.stdin.flush().await.map_err(|e| e.to_string())
    }

    /// The next message, after answering any request the server makes of us.
    async fn read(&mut self) -> Result<Msg, String> {
        loop {
            let line = self
                .lines
                .next_line()
                .await
                .map_err(|e| e.to_string())?
                .ok_or("Codex stopped")?;
            match classify(&line) {
                Msg::Request { id } => {
                    let refusal = json!({ "id": id, "error": { "code": -32601, "message": "not available in this chat" } });
                    self.write(&refusal).await?;
                }
                other => return Ok(other),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Lines recorded from codex-cli 0.159 app-server (trimmed).
    #[test]
    fn messages() {
        assert_eq!(
            classify(r#"{"id":2,"result":{"thread":{"id":"01a0f961"}}}"#),
            Msg::Response {
                id: 2,
                result: json!({ "thread": { "id": "01a0f961" } })
            }
        );
        assert_eq!(
            classify(
                r#"{"method":"item/agentMessage/delta","params":{"threadId":"t","turnId":"u","itemId":"i","delta":"tamarindo"}}"#
            ),
            Msg::Delta("tamarindo".into())
        );
        assert_eq!(
            classify(
                r#"{"method":"turn/completed","params":{"threadId":"t","turn":{"id":"u","items":[],"status":"completed","error":null}}}"#
            ),
            Msg::TurnDone { error: None }
        );
        assert_eq!(
            classify(
                r#"{"method":"turn/completed","params":{"turn":{"status":"failed","error":{"message":"usage limit reached"}}}}"#
            ),
            Msg::TurnDone {
                error: Some("usage limit reached".into())
            }
        );
        assert_eq!(
            classify(r#"{"id":"s1","method":"item/commandExecution/requestApproval","params":{}}"#),
            Msg::Request { id: json!("s1") }
        );
        assert_eq!(
            classify(r#"{"method":"error","params":{"error":{"message":"x"},"willRetry":true}}"#),
            Msg::Other
        );
        assert_eq!(
            classify(r#"{"method":"remoteControl/status/changed","params":{}}"#),
            Msg::Other
        );
        assert_eq!(
            classify(r#"{"id":4,"error":{"code":-1,"message":"no such thread"}}"#),
            Msg::Failure {
                id: 4,
                message: "no such thread".into()
            }
        );
    }
}
