// Generated by `cargo run -p vultures-ai-brand --example gen-ts`. Do not edit.
export const SLUG = "vultures-ai";
export const NAME = "Vultures AI";
export const BUNDLE_ID = "io.github.rogeriojunior31.vultures-ai";
