//! The app's name, in one place. Renaming the project means editing this file and
//! running `cargo run -p vults-brand --example gen-ts` to refresh `ui/src/brand.ts`.
//! The OS keyring is keyed by `BUNDLE_ID` and the agents' configs name `HOOK_BIN`: a rename
//! keeps the old values below, so the app can move what an older install left behind.

/// Lower-case slug: socket/pipe, folders, keyring service, binaries.
pub const SLUG: &str = "vults";
/// Display name: window titles, tray, user-facing text.
pub const NAME: &str = "Vults";
pub const BUNDLE_ID: &str = "io.github.rogeriojunior31.vults";
/// Prefix of every environment variable the app reads.
pub const ENV_PREFIX: &str = "VULTS_";
/// Name of the hook binary the agents run, without the platform extension.
pub const HOOK_BIN: &str = "vults-hook";
pub const HOOK_EXE: &str = if cfg!(windows) {
    "vults-hook.exe"
} else {
    "vults-hook"
};

/// The names before the project became Vults (0.1.5 and older): folders, keyring service and
/// hook entries an upgrade still finds and moves.
pub const LEGACY_SLUG: &str = "vultures-ai";
pub const LEGACY_NAME: &str = "Vultures AI";
pub const LEGACY_BUNDLE_ID: &str = "io.github.rogeriojunior31.vultures-ai";
pub const LEGACY_HOOK_BIN: &str = "vultures-ai-hook";

/// The TypeScript twin of these constants, committed as `ui/src/brand.ts`.
pub fn typescript() -> String {
    format!(
        "// Generated by `cargo run -p vults-brand --example gen-ts`. Do not edit.\n\
         export const SLUG = {SLUG:?};\n\
         export const NAME = {NAME:?};\n\
         export const BUNDLE_ID = {BUNDLE_ID:?};\n"
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn ui_brand_ts_is_up_to_date() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../ui/src/brand.ts");
        let committed = std::fs::read_to_string(path).unwrap_or_default();
        assert_eq!(
            committed,
            super::typescript(),
            "ui/src/brand.ts is stale: run `cargo run -p vults-brand --example gen-ts`"
        );
    }

    #[test]
    fn hook_exe_is_the_hook_bin() {
        assert!(super::HOOK_EXE.starts_with(super::HOOK_BIN));
    }
}
