//! The app's name, in one place. Renaming the project means editing this file and
//! running `cargo run -p vultures-ai-brand --example gen-ts` to refresh `ui/src/brand.ts`.
//! `BUNDLE_ID` must never change after the first release: the OS keyring is keyed by it.

/// Lower-case slug: socket/pipe, folders, keyring service, binaries.
pub const SLUG: &str = "vultures-ai";
/// Display name: window titles, tray, user-facing text.
pub const NAME: &str = "Vultures AI";
pub const BUNDLE_ID: &str = "io.github.rogeriojunior31.vultures-ai";
/// Prefix of every environment variable the app reads.
pub const ENV_PREFIX: &str = "VULTURES_AI_";
/// Name of the hook binary the agents run, without the platform extension.
pub const HOOK_BIN: &str = "vultures-ai-hook";
pub const HOOK_EXE: &str = if cfg!(windows) {
    "vultures-ai-hook.exe"
} else {
    "vultures-ai-hook"
};

/// The TypeScript twin of these constants, committed as `ui/src/brand.ts`.
pub fn typescript() -> String {
    format!(
        "// Generated by `cargo run -p vultures-ai-brand --example gen-ts`. Do not edit.\n\
         export const SLUG = {SLUG:?};\n\
         export const NAME = {NAME:?};\n\
         export const BUNDLE_ID = {BUNDLE_ID:?};\n"
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn ui_brand_ts_is_up_to_date() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../ui/src/brand.ts");
        let committed = std::fs::read_to_string(path).unwrap_or_default();
        assert_eq!(
            committed,
            super::typescript(),
            "ui/src/brand.ts is stale: run `cargo run -p vultures-ai-brand --example gen-ts`"
        );
    }

    #[test]
    fn hook_exe_is_the_hook_bin() {
        assert!(super::HOOK_EXE.starts_with(super::HOOK_BIN));
    }
}
