import type { SpriteSet } from "../sprites";
import data from "./zeca.json";

/** Zeca, the black vulture. Generated by design/mascots/zeca/zeca.py: do not edit the JSON. */
export const ZECA = data as unknown as SpriteSet;

/** Perched frames: the body's top-left sits this far above the wire. */
export const PERCH_HEIGHT = 20;

/** The same for any species: taller birds sit higher above the wire. */
export const perchOf = (set: SpriteSet): number => set.perch ?? PERCH_HEIGHT;
