// The tray icon's frames (app/icons/tray/, generated by design/mascots/zeca/zeca.py): each state's
// frames at 1x and 4x, on a dark and a light panel, as a panel would show them.
import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";

const STATES = ["idle", "working", "needs-you", "done", "failed"];
const FRAMES = 2;

const uri = (name: string) =>
  `data:image/png;base64,${readFileSync(new URL(`../../app/icons/tray/${name}.png`, import.meta.url)).toString("base64")}`;

for (const state of STATES) {
  test(`tray: ${state}`, async ({ page }) => {
    const frames = Array.from({ length: FRAMES }, (_, n) => uri(`${state}-${n}`));
    const panel = (bg: string) =>
      `<div style="display:flex;gap:8px;align-items:end;padding:8px;background:${bg}">` +
      frames.map((src) => `<img src="${src}" width="32" height="32"><img src="${src}" width="128" height="128">`).join("") +
      "</div>";
    await page.setContent(
      `<body style="margin:0"><style>img{image-rendering:pixelated}</style>` +
        `<div id="tray" style="display:inline-block">${panel("#1d1f24")}${panel("#eff0f1")}</div></body>`,
    );
    await expect(page.locator("#tray")).toHaveScreenshot(`tray-${state}.png`);
  });
}
