// The tray icon's frames (app/icons/tray/<size>/, generated by design/mascots/zeca/zeca.py): each
// state's frames at every native size (22 px is Plasma's default panel, then 24 and 32), at 1x as
// the panel shows them and at 4x to read the pixels, on a dark and a light panel.
import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";

const STATES = ["idle", "working", "needs-you", "done", "failed"];
const SIZES = [22, 24, 32];
const FRAMES = 2;

const uri = (size: number, name: string) =>
  `data:image/png;base64,${readFileSync(new URL(`../../app/icons/tray/${size}/${name}.png`, import.meta.url)).toString("base64")}`;

for (const state of STATES) {
  test(`tray: ${state}`, async ({ page }) => {
    const panel = (bg: string) =>
      `<div style="display:flex;gap:8px;align-items:end;padding:8px;background:${bg}">` +
      SIZES.map((size) =>
        Array.from({ length: FRAMES }, (_, n) => uri(size, `${state}-${n}`))
          .map((src) => `<img src="${src}" width="${size}" height="${size}">`)
          .join(""),
      ).join("") +
      SIZES.map((size) =>
        Array.from({ length: FRAMES }, (_, n) => uri(size, `${state}-${n}`))
          .map((src) => `<img src="${src}" width="${size * 4}" height="${size * 4}">`)
          .join(""),
      ).join("") +
      "</div>";
    await page.setContent(
      `<body style="margin:0"><style>img{image-rendering:pixelated}</style>` +
        `<div id="tray" style="display:inline-block">${panel("#1d1f24")}${panel("#eff0f1")}</div></body>`,
    );
    await expect(page.locator("#tray")).toHaveScreenshot(`tray-${state}.png`);
  });
}
