//! The tray icon: Zeca in the panel, showing the flock's state, and the way to the island (a left
//! click opens it). It only draws attention: it never answers a card (rule 2).
//!
//! On Linux it is our own StatusNotifierItem (`platform::tray`): the toolkit's tray cannot hear a
//! left click there, and changes its icon by writing files. Elsewhere it is Tauri's, still.

use tauri::{AppHandle, Manager};
use vultures_ai_core::{Attention, Presence, Status, ViewModel};

use crate::ISLAND;

/// What the icon shows, picked from core's view: core says what it means, the icon draws it.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Look {
    #[default]
    Idle,
    Working,
    /// A permission or a question waits: the loudest.
    NeedsYou,
    Done,
    Failed,
}

impl Look {
    pub fn of(view: &ViewModel) -> Self {
        match view.attention {
            Attention::NeedsYou => Look::NeedsYou,
            Attention::Failed => Look::Failed,
            Attention::Done => Look::Done,
            Attention::Info | Attention::Quiet => {
                let busy = view
                    .sessions
                    .iter()
                    .any(|s| matches!(s.status, Status::Thinking | Status::Working | Status::RateLimited));
                if busy { Look::Working } else { Look::Idle }
            }
        }
    }

    /// Its frames (generated by `design/mascots/zeca/zeca.py`), each with how long it holds.
    /// A blink now and then at rest; the rest move slowly, so the panel is not busy.
    #[cfg_attr(not(target_os = "linux"), allow(dead_code))]
    fn frames(self) -> [(&'static [u8], u64); 2] {
        macro_rules! png {
            ($name:literal) => {
                include_bytes!(concat!("../icons/tray/", $name, ".png")).as_slice()
            };
        }
        match self {
            Look::Idle => [(png!("idle-0"), 4000), (png!("idle-1"), 200)],
            Look::Working => [(png!("working-0"), 600), (png!("working-1"), 600)],
            Look::NeedsYou => [(png!("needs-you-0"), 700), (png!("needs-you-1"), 500)],
            Look::Done => [(png!("done-0"), 700), (png!("done-1"), 700)],
            Look::Failed => [(png!("failed-0"), 500), (png!("failed-1"), 500)],
        }
    }
}

/// The look the icon should show now; the tray's own task follows it.
#[derive(Default)]
pub struct TrayLook(std::sync::Mutex<Option<tokio::sync::watch::Sender<Look>>>);

/// Called with every new view.
pub fn show(app: &AppHandle, view: &ViewModel) {
    if let Some(state) = app.try_state::<TrayLook>()
        && let Ok(slot) = state.0.lock()
        && let Some(tx) = slot.as_ref()
    {
        tx.send_if_modified(|look| {
            let next = Look::of(view);
            std::mem::replace(look, next) != next
        });
    }
}

/// The presets in the menu, by entry id.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
const PRESETS: [(&str, Presence, &str); 4] = [
    ("preset-island", Presence::Island, "Island"),
    ("preset-panel", Presence::Panel, "Panel"),
    ("preset-quiet", Presence::Quiet, "Quiet"),
    ("preset-paused", Presence::Paused, "Paused"),
];

/// The menu: what each entry does.
fn pick(app: &AppHandle, id: &str) {
    use tauri::Emitter;
    match id {
        "chat" if crate::settings::zeca(app) => {
            let _ = app.emit_to(ISLAND, "open-chat", ());
        }
        "setup" => crate::open_settings(app, Some("agents")),
        "quit" => app.exit(0),
        _ => {
            if let Some((_, presence, _)) = PRESETS.iter().find(|(p, ..)| *p == id)
                && let Err(e) = crate::panel::set(app, *presence)
            {
                tracing::warn!("preset not switched: {e}");
            }
        }
    }
}

/// The menu as it stands: the preset in use is the one marked.
#[cfg(target_os = "linux")]
fn entries(app: &AppHandle) -> Vec<vultures_ai_platform::tray::Entry> {
    use vultures_ai_platform::tray::Entry;
    let now = crate::panel::presence(app);
    // No chat without Zeca (ADR 0010).
    let chat = crate::settings::zeca(app).then(|| Entry::Item {
        id: "chat",
        label: "Chat…".into(),
    });
    chat.into_iter()
        .chain([
            Entry::Item {
                id: "setup",
                label: "Set up agents…".into(),
            },
            Entry::Choice {
                options: PRESETS
                    .iter()
                    .map(|(id, _, label)| (*id, (*label).into()))
                    .collect(),
                selected: PRESETS.iter().position(|(_, p, _)| *p == now).unwrap_or(0),
            },
            Entry::Item {
                id: "quit",
                label: "Quit".into(),
            },
        ])
        .collect()
}

/// The live tray item, once the panel took it.
#[cfg(target_os = "linux")]
#[derive(Default)]
struct TrayItem(std::sync::OnceLock<std::sync::Arc<vultures_ai_platform::tray::Tray>>);

/// Rebuilds the menu (the preset changed). From any thread.
pub fn refresh_menu(app: &AppHandle) {
    #[cfg(target_os = "linux")]
    if let Some(item) = app.try_state::<TrayItem>().and_then(|t| t.0.get().cloned()) {
        let entries = entries(app);
        tauri::async_runtime::spawn(async move { item.set_entries(entries).await });
    }
    #[cfg(not(target_os = "linux"))]
    let _ = app;
}

#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
/// A left click (or a notification's *Open*): the island opens (in Panel mode, by the panel).
/// With a card waiting, it is already open on it; the click only brings it up.
pub(crate) fn activate(app: &AppHandle) {
    use tauri::Emitter;
    crate::panel::apply(app);
    let _ = app.emit_to(ISLAND, "shortcut", "open");
}

#[cfg(target_os = "linux")]
pub fn start(app: &AppHandle) -> tauri::Result<()> {
    use vultures_ai_platform::tray;

    let (tx, mut rx) = tokio::sync::watch::channel(Look::Idle);
    app.manage(TrayLook(std::sync::Mutex::new(Some(tx))));
    app.manage(TrayItem::default());
    let entries = entries(app);
    let (on_click, on_pick, motion) = (app.clone(), app.clone(), app.clone());
    tauri::async_runtime::spawn(async move {
        let icon = |png: &[u8]| {
            tray::icon_from_png(png).unwrap_or_else(|| tray::Icon {
                width: 0,
                height: 0,
                data: Vec::new(),
            })
        };
        let first = icon(Look::Idle.frames()[0].0);
        let item = tray::spawn(
            vultures_ai_brand::SLUG,
            vultures_ai_brand::NAME,
            first,
            entries,
            move |x, y| {
                tracing::debug!(x, y, "tray clicked");
                activate(&on_click);
            },
            move |id| pick(&on_pick, id),
        )
        .await;
        let item = match item {
            Ok(item) => std::sync::Arc::new(item),
            Err(e) => {
                tracing::warn!("no tray on this desktop: {e}");
                return;
            }
        };
        let _ = motion.state::<TrayItem>().0.set(item.clone());
        // A preset switched before the item was up.
        refresh_menu(&motion);
        loop {
            let look = *rx.borrow_and_update();
            let attention = look == Look::NeedsYou;
            let frames = look.frames();
            // Reduced motion: the first frame only, until the look changes. Read at each change,
            // so the desktop's switch applies from the next one.
            if !animations(&motion).await {
                item.show(icon(frames[0].0), attention).await;
                if rx.changed().await.is_err() {
                    return;
                }
                continue;
            }
            for (png, ms) in frames.iter().cycle() {
                item.show(icon(png), attention).await;
                match tokio::time::timeout(std::time::Duration::from_millis(*ms), rx.changed()).await {
                    Ok(Ok(())) => break,
                    Ok(Err(_)) => return,
                    Err(_) => {}
                }
            }
        }
    });
    Ok(())
}

/// Whether the desktop allows animations, read on GTK's thread.
#[cfg(target_os = "linux")]
async fn animations(app: &AppHandle) -> bool {
    let (tx, rx) = tokio::sync::oneshot::channel();
    let _ = app.run_on_main_thread(move || {
        let _ = tx.send(vultures_ai_platform::linux::animations_enabled());
    });
    rx.await.unwrap_or(true)
}

#[cfg(not(target_os = "linux"))]
pub fn start(app: &AppHandle) -> tauri::Result<()> {
    use tauri::menu::{Menu, MenuItem};
    use tauri::tray::TrayIconBuilder;

    let chat = MenuItem::with_id(app, "chat", "Chat…", true, None::<&str>)?;
    let setup = MenuItem::with_id(app, "setup", "Set up agents…", true, None::<&str>)?;
    let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&chat, &setup, &quit])?;
    let mut tray = TrayIconBuilder::with_id("main")
        .tooltip(vultures_ai_brand::NAME)
        .menu(&menu)
        .on_menu_event(|app, event| pick(app, event.id().as_ref()));
    if let Some(icon) = app.default_window_icon() {
        tray = tray.icon(icon.clone());
    }
    tray.build(app)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vultures_ai_core::State;

    #[test]
    fn every_look_has_its_frames_at_one_size() {
        for look in [
            Look::Idle,
            Look::Working,
            Look::NeedsYou,
            Look::Done,
            Look::Failed,
        ] {
            for (png, ms) in look.frames() {
                assert!(ms >= 200, "{look:?}: a low rate");
                #[cfg(target_os = "linux")]
                {
                    let icon = vultures_ai_platform::tray::icon_from_png(png).expect("an RGBA PNG");
                    assert_eq!((icon.width, icon.height, icon.data.len()), (32, 32, 32 * 32 * 4));
                }
                #[cfg(not(target_os = "linux"))]
                assert!(!png.is_empty());
            }
        }
    }

    #[test]
    fn the_look_follows_cores_attention() {
        let view = State::default().view();
        assert_eq!(Look::of(&view), Look::Idle);
        let mut view = view;
        for (attention, look) in [
            (Attention::NeedsYou, Look::NeedsYou),
            (Attention::Failed, Look::Failed),
            (Attention::Done, Look::Done),
            (Attention::Quiet, Look::Idle),
        ] {
            view.attention = attention;
            assert_eq!(Look::of(&view), look);
        }
    }
}
