//! What differs between agents: event names, tool names, where their config lives and what
//! the installer adds to it. Everything else in the app is agent-agnostic.

mod antigravity;
mod claude;
mod codex;
mod diff;
mod gemini;
mod opencode;
mod other;
pub mod usage;

use std::path::{Path, PathBuf};

use serde_json::Value;
use vults_agent_config::HookEntry;
use vults_core::{AgentUpdate, Ask};
use vults_protocol::{AgentKind, Event};

pub use antigravity::Antigravity;
pub use claude::Claude;
pub use codex::{Codex, Trust as CodexTrust, trust as codex_trust};
pub use gemini::Gemini;
pub use opencode::OPENCODE;

pub trait Agent: Send + Sync {
    fn kind(&self) -> AgentKind;
    /// Normalizes a hook event; `None` for events the app ignores.
    fn parse(&self, event: &Event) -> Option<AgentUpdate>;
    /// The file the installer edits, under the user's home.
    fn config_file(&self, home: &Path) -> PathBuf;
    /// What the installer adds to that file.
    fn hook_entries(&self, hook_exe: &Path) -> Vec<HookEntry>;
    /// A statusLine command for the same file, when the agent reports usage only there.
    fn status_line(&self, _hook_exe: &Path) -> Option<String> {
        None
    }
    /// `config` with our entries (re)installed. Most agents keep Claude Code's `hooks` object.
    fn install(&self, config: &Value, hook_exe: &Path) -> Value {
        vults_agent_config::with_ours(config, &self.hook_entries(hook_exe), MARKER)
    }
    /// Why installing into `config` would overwrite something of the user's; nothing is written then.
    fn install_blocked(&self, _config: &Value) -> Option<String> {
        None
    }
    /// `config` without our entries, and nothing else changed.
    fn uninstall(&self, config: &Value) -> Value {
        vults_agent_config::remove_ours(config, MARKER)
    }
    fn installed(&self, config: &Value) -> bool {
        vults_agent_config::has_ours(config, MARKER)
    }
    /// Our entries in `config` are exactly what [`Agent::install`] would write for `hook_exe`.
    fn up_to_date(&self, config: &Value, hook_exe: &Path) -> bool {
        vults_agent_config::ours_match(config, &self.hook_entries(hook_exe), MARKER)
    }
    /// The command of our first entry: which hook binary the config runs.
    fn our_command<'a>(&self, config: &'a Value) -> Option<&'a str> {
        vults_agent_config::our_command(config, MARKER)
    }
}

/// A built-in agent: the ones the installer knows. Other tools install their hooks themselves.
pub fn agent(kind: AgentKind) -> Option<&'static dyn Agent> {
    match kind {
        AgentKind::Claude => Some(&Claude),
        AgentKind::Codex => Some(&Codex),
        AgentKind::Gemini => Some(&Gemini),
        // Set up with a plugin file, not hooks: see [`plugin`].
        AgentKind::OpenCode | AgentKind::Other => None,
    }
}

/// An agent the installer can set up, by the name `--agent` gives it: the built-in ones, and
/// tools that go by their own name but have a config we know how to edit.
pub fn installable(name: &str) -> Option<&'static dyn Agent> {
    match name {
        antigravity::NAME => Some(&Antigravity),
        _ => agent(AgentKind::parse(name)?),
    }
}

/// An agent set up with a whole file of ours that it loads by itself (a plugin), instead of
/// entries in its config. `name` is what the plugin passes to `--agent`.
#[derive(Debug)]
pub struct PluginAgent {
    pub name: &'static str,
    /// Where the file goes, from the user's config folder (`$XDG_CONFIG_HOME` or `~/.config`).
    pub file: fn(&Path) -> PathBuf,
    /// The file, running `hook_exe`.
    pub text: fn(&Path) -> String,
}

/// A plugin agent the installer can set up, by the name its sessions arrive with.
pub fn plugin(name: &str) -> Option<&'static PluginAgent> {
    match name {
        opencode::NAME => Some(&OPENCODE),
        _ => None,
    }
}

/// The line that makes a plugin file ours: a file without it is the user's and stays untouched.
pub fn plugin_marker() -> String {
    format!("Generated by {}", vults_brand::NAME)
}

/// Normalizes a hook event from any agent; `None` for events the app ignores.
pub fn parse(event: &Event) -> Option<AgentUpdate> {
    match event.agent {
        AgentKind::Other => other::parse(event),
        AgentKind::OpenCode => opencode::parse(event),
        kind => agent(kind)?.parse(event),
    }
}

/// What the agent shows while a permission waits for a click on the island.
const WAITING: &str = "Waiting for your answer on the island";

/// Our entries are recognized by the hook binary's name in their command.
pub const MARKER: &str = vults_brand::HOOK_BIN;

/// `'<exe>' --agent <agent> <Event>`, safe for the POSIX shell the agents run hooks with
/// (Git Bash on Windows, hence forward slashes there).
pub fn hook_command(hook_exe: &Path, agent: &str, event: &str) -> String {
    let exe = hook_exe.to_string_lossy();
    let exe = if cfg!(windows) {
        exe.replace('\\', "/")
    } else {
        exe.into_owned()
    };
    format!("'{}' --agent {agent} {event}", exe.replace('\'', r"'\''"))
}

/// The hook binary a command from [`hook_command`] runs, as written there.
pub fn hook_exe_of(command: &str) -> Option<PathBuf> {
    let quoted = command.strip_prefix('\'')?;
    let end = quoted.find("' --agent ")?;
    Some(PathBuf::from(quoted[..end].replace(r"'\''", "'")))
}

/// The hook binary our entries in `config` run, when they are what `hook_exe` would get except
/// for that path (another data folder, another build). Saying "an older version" then would send
/// the user looking for an update that does not exist.
pub fn other_hook(agent: &dyn Agent, config: &Value, hook_exe: &Path) -> Option<PathBuf> {
    let exe = hook_exe_of(agent.our_command(config)?)?;
    (!agent.up_to_date(config, hook_exe) && agent.up_to_date(config, &exe)).then_some(exe)
}

/// What a step shows next to its verb, most specific field first.
const DETAIL_FIELDS: &[&str] = &[
    "command",
    "file_path",
    "path",
    "notebook_path",
    "url",
    "query",
    "pattern",
];
/// What an approval card shows: the exact thing Allow authorizes.
const TARGET_FIELDS: &[&str] = &[
    "command",
    "file_path",
    "path",
    "notebook_path",
    "url",
    "query",
    "pattern",
    "prompt",
    "description",
];

fn first_field<'a>(input: &'a serde_json::Value, fields: &[&'static str]) -> Option<(&'static str, &'a str)> {
    fields.iter().find_map(|&f| {
        let v = input.get(f)?.as_str()?.trim();
        (!v.is_empty()).then_some((f, v))
    })
}

/// `github · list_prs` for `mcp__github__list_prs`: the server and its tool.
pub(crate) fn mcp_label(tool: &str) -> Option<String> {
    let (server, name) = tool.strip_prefix("mcp__")?.split_once("__")?;
    Some(format!("{server} · {name}"))
}

/// `main.rs` for a file, the first 40 characters of a command or query.
pub(crate) fn detail(input: &serde_json::Value) -> Option<String> {
    let (field, value) = first_field(input, DETAIL_FIELDS)?;
    Some(match field {
        "file_path" | "path" | "notebook_path" => file_name(value),
        _ => shorten(value, 40),
    })
}

/// How much of the acted-on value a target keeps (its first line, at most this many characters).
const TARGET_MAX: usize = 300;

/// `Bash · rm -rf build`: the tool and the exact thing it would act on.
pub(crate) fn target(tool: &str, input: &serde_json::Value) -> String {
    match first_field(input, TARGET_FIELDS) {
        Some((_, value)) => format!("{tool} · {}", shorten(value, TARGET_MAX)),
        None => tool.to_string(),
    }
}

/// Last path component, for step details: `Editing main.rs`, not the whole path.
pub(crate) fn file_name(path: &str) -> String {
    path.trim_end_matches(['/', '\\'])
        .rsplit(['/', '\\'])
        .next()
        .unwrap_or(path)
        .to_string()
}

/// First `max` characters, on a char boundary, with an ellipsis when cut.
pub(crate) fn shorten(text: &str, max: usize) -> String {
    let text = text.trim();
    let line = text.lines().next().unwrap_or("");
    match line.char_indices().nth(max) {
        Some((i, _)) => format!("{}…", &line[..i]),
        None if line.len() < text.len() => format!("{line}…"),
        None => line.to_string(),
    }
}

/// A whole command is shown on the card when the target (one line, 300 characters) cuts it; past
/// this it would not fit the card anyway.
const MAX_FULL: usize = 2_000;

/// What a permission card shows besides the target: the agent's description of the action, the
/// whole command when the target cut it, and the lines an edit adds and removes.
pub fn ask(tool: &str, input: &Value) -> Ask {
    let text = |k: &str| input.get(k).and_then(Value::as_str);
    let full = match (tool, text("command")) {
        // A patch's command is the patch itself: its files and line counts say it better.
        ("apply_patch", _) | (_, None) => None,
        (_, Some(cmd)) => {
            let cmd = cmd.trim();
            (cmd.lines().count() > 1 || cmd.chars().count() > TARGET_MAX)
                .then(|| cmd.chars().take(MAX_FULL).collect())
        }
    };
    let (added, removed) = match tool {
        "Edit" => changed(
            text("old_string").unwrap_or_default(),
            text("new_string").unwrap_or_default(),
        ),
        "MultiEdit" => input
            .get("edits")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .map(|e| {
                let side = |k: &str| e.get(k).and_then(Value::as_str).unwrap_or_default();
                changed(side("old_string"), side("new_string"))
            })
            .fold((0, 0), |(a, r), (da, dr)| (a + da, r + dr)),
        "Write" => (count_lines(text("content").unwrap_or_default()), 0),
        "apply_patch" => patch_lines(text("command").unwrap_or_default()),
        _ => (0, 0),
    };
    // A patch's target names its files, which are never cut.
    let cut = tool != "apply_patch"
        && first_field(input, TARGET_FIELDS).is_some_and(|(_, v)| shorten(v, TARGET_MAX) != v);
    Ask {
        description: text("description").and_then(filled),
        full,
        cut,
        added,
        removed,
    }
}

fn count_lines(text: &str) -> u32 {
    text.lines().count() as u32
}

/// Lines added and removed going from `old` to `new`: what is left once the lines both share at
/// the start and at the end are set aside. Not a real diff, but right for the usual edit.
fn changed(old: &str, new: &str) -> (u32, u32) {
    let old: Vec<&str> = old.lines().collect();
    let new: Vec<&str> = new.lines().collect();
    let head = old.iter().zip(&new).take_while(|(a, b)| a == b).count();
    let tail = old[head..]
        .iter()
        .rev()
        .zip(new[head..].iter().rev())
        .take_while(|(a, b)| a == b)
        .count();
    ((new.len() - head - tail) as u32, (old.len() - head - tail) as u32)
}

/// `+` and `-` lines of a patch, leaving out its headers.
fn patch_lines(patch: &str) -> (u32, u32) {
    patch.lines().fold((0, 0), |(a, r), l| {
        if l.starts_with("+++") || l.starts_with("---") {
            (a, r)
        } else if l.starts_with('+') {
            (a + 1, r)
        } else if l.starts_with('-') {
            (a, r + 1)
        } else {
            (a, r)
        }
    })
}

/// Text an agent sent, or nothing when it sent only blanks.
pub(crate) fn filled(text: &str) -> Option<String> {
    let text = text.trim();
    (!text.is_empty()).then(|| text.to_string())
}

/// A finished card shows one line, not the reply's later paragraphs, tables or markdown.
const SUMMARY_MAX: usize = 200;

/// The first paragraph of a reply with text in it, as plain text on one line. A paragraph ends
/// at a blank line, a `---`/`***`/`___` rule or a `|` table row.
pub(crate) fn summary_line(text: &str) -> Option<String> {
    let mut paragraph = Vec::new();
    let mut title = None;
    for line in text.lines().chain([""]) {
        let t = line.trim();
        let rule = t.chars().count() >= 3 && ['-', '*', '_'].iter().any(|&c| t.chars().all(|x| x == c));
        if !(t.is_empty() || rule || t.starts_with('|')) {
            paragraph.push(t);
            continue;
        }
        let only_headings = paragraph.iter().all(|l| heading(l).is_some());
        let line = plain(paragraph.drain(..));
        if line.is_empty() {
            continue;
        }
        // `## Summary` alone says nothing; the paragraph under it does.
        if only_headings {
            title.get_or_insert(line);
            continue;
        }
        return Some(capped(line));
    }
    title.map(capped)
}

fn plain<'a>(lines: impl Iterator<Item = &'a str>) -> String {
    let mut out = String::new();
    for l in lines {
        let l = l.replace("**", "").replace("__", "").replace('`', "");
        for word in unbullet(heading(&l).unwrap_or(&l).trim()).split_whitespace() {
            if !out.is_empty() {
                out.push(' ');
            }
            out.push_str(word);
        }
    }
    out
}

fn capped(line: String) -> String {
    match line.char_indices().nth(SUMMARY_MAX) {
        Some((i, _)) => format!("{}…", line[..i].trim_end()),
        None => line,
    }
}

/// The text of a markdown heading: 1 to 6 `#` then a space or nothing. `#48`, `#!/bin/sh` and
/// `#[derive]` are text.
fn heading(line: &str) -> Option<&str> {
    let rest = line.trim_start_matches('#');
    let hashes = line.len() - rest.len();
    ((1..=6).contains(&hashes) && (rest.is_empty() || rest.starts_with(char::is_whitespace))).then_some(rest)
}

/// `- `, `* `, `• ` or `1. ` at the start of a list item.
fn unbullet(line: &str) -> &str {
    if let Some(rest) = ["- ", "* ", "• "].iter().find_map(|b| line.strip_prefix(b)) {
        return rest;
    }
    let digits = line.len() - line.trim_start_matches(|c: char| c.is_ascii_digit()).len();
    match line[digits..].strip_prefix('.') {
        Some(rest) if digits > 0 && rest.starts_with(char::is_whitespace) => rest,
        _ => line,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn commands_are_quoted_for_the_shell() {
        assert_eq!(
            hook_command(Path::new("/home/me/bin/vults-hook"), "claude", "Stop"),
            "'/home/me/bin/vults-hook' --agent claude Stop"
        );
        assert_eq!(
            hook_command(Path::new("/it's/hook"), "claude", "Stop"),
            r"'/it'\''s/hook' --agent claude Stop"
        );
        assert!(hook_command(Path::new("/x/vults-hook"), "claude", "Stop").contains(MARKER));
    }

    #[test]
    fn the_hook_a_command_runs() {
        for exe in ["/home/me/.local/share/vults/vults-hook", "/it's/hook"] {
            for event in ["Stop", "--ask PreToolUse"] {
                let command = hook_command(Path::new(exe), "claude", event);
                assert_eq!(hook_exe_of(&command), Some(PathBuf::from(exe)));
            }
        }
        assert_eq!(hook_exe_of("vults-hook --agent claude Stop"), None);
        assert_eq!(hook_exe_of("'/x/vults-hook'"), None);
    }

    #[test]
    fn hooks_from_another_folder_are_not_an_older_version() {
        use vults_agent_config::with_ours;
        let (here, there) = (Path::new("/here/vults-hook"), Path::new("/there/vults-hook"));
        for kind in [AgentKind::Claude, AgentKind::Codex, AgentKind::Gemini] {
            let a = agent(kind).unwrap();
            let elsewhere = with_ours(&serde_json::json!({}), &a.hook_entries(there), MARKER);
            assert_eq!(
                other_hook(a, &elsewhere, here),
                Some(there.to_path_buf()),
                "{kind:?}"
            );
            // Up to date: nothing to say.
            assert_eq!(other_hook(a, &elsewhere, there), None, "{kind:?}");
            // Another path and an older entry: that is an older version.
            let mut older = elsewhere.clone();
            let event = a.hook_entries(there)[0].event;
            older["hooks"][event][0]["hooks"][0]["timeout"] = 1234.into();
            assert_eq!(other_hook(a, &older, here), None, "{kind:?}");
        }
    }

    /// Claude Code settings with the user's own status line, through the installer's whole change
    /// (hooks and statusLine): their line is saved beside the hook and comes back byte for byte.
    #[test]
    fn the_users_own_status_line_survives_install_and_removal() {
        use vults_agent_config::status_line;
        let a = agent(AgentKind::Claude).unwrap();
        let exe = Path::new("/data/vults-hook");
        let dir = std::env::temp_dir().join(format!("vults-agents-sl-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let (config, sidecar) = (dir.join("settings.json"), dir.join(status_line::PREVIOUS_FILE));
        let original = include_str!("../tests/fixtures/claude-settings-own-status-line.json");
        std::fs::write(&config, original).unwrap();

        let command = a.status_line(exe).unwrap();
        let entries = a.hook_entries(exe);
        let run = |install: bool| {
            let change = |v: &Value, saved: Option<&Value>| {
                if install {
                    let v = vults_agent_config::with_ours(v, &entries, MARKER);
                    status_line::install(&v, saved, &command, MARKER)
                } else {
                    let v = vults_agent_config::remove_ours(v, MARKER);
                    status_line::uninstall(&v, saved, MARKER)
                }
            };
            let plan = status_line::preview(&config, &sidecar, change).unwrap();
            status_line::apply(
                &config,
                &sidecar,
                &plan.fingerprint,
                change,
                std::time::SystemTime::now(),
            )
            .unwrap();
        };

        run(true);
        let installed = vults_agent_config::read_json(&config).unwrap();
        assert_eq!(installed["statusLine"]["command"], command.as_str());
        assert_eq!(installed["statusLine"]["padding"], 0);
        let saved: Value = serde_json::from_slice(&std::fs::read(&sidecar).unwrap()).unwrap();
        assert_eq!(saved["command"], "bash ~/.claude/statusline.sh");

        run(false);
        assert_eq!(std::fs::read_to_string(&config).unwrap(), original);
        assert!(!sidecar.exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A config as the user keeps it: their keys around `hooks`, every key sorted (as some tools
    /// write them), our entries running the hook from another folder. Moving them to this hook
    /// must change only the lines that name it.
    #[test]
    fn an_update_touches_only_our_lines() {
        fn sorted(v: &Value) -> Value {
            match v {
                Value::Object(m) => {
                    let mut keys: Vec<_> = m.keys().collect();
                    keys.sort();
                    Value::Object(keys.into_iter().map(|k| (k.clone(), sorted(&m[k]))).collect())
                }
                Value::Array(a) => Value::Array(a.iter().map(sorted).collect()),
                v => v.clone(),
            }
        }
        use vults_agent_config as config;
        let (old, new) = (Path::new("/old/vults-hook"), Path::new("/new/vults-hook"));
        let dir = std::env::temp_dir().join(format!("vults-agents-order-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();

        for kind in [AgentKind::Claude, AgentKind::Codex, AgentKind::Gemini] {
            let a = agent(kind).unwrap();
            let install = |v: &Value, exe: &Path| {
                let v = config::with_ours(v, &a.hook_entries(exe), MARKER);
                match a.status_line(exe) {
                    Some(c) => config::status_line::with_ours(&v, &c, MARKER),
                    None => v,
                }
            };
            let user = serde_json::json!({ "hooks": {
                "AAA": [ { "hooks": [ { "type": "command", "command": "other-tool" } ] } ],
                "zzz": [ { "hooks": [ { "type": "command", "command": "keep-me" } ] } ]
            } });
            // The user's key first, then the hooks with our events in install order.
            let mut installed =
                serde_json::json!({ "security": { "auth": { "selectedType": "oauth-personal" } } });
            for (k, v) in install(&user, old).as_object().unwrap() {
                installed[k] = v.clone();
            }

            for file in [installed.clone(), sorted(&installed)] {
                let path = dir.join(format!("{kind:?}.json"));
                std::fs::write(&path, serde_json::to_string_pretty(&file).unwrap() + "\n").unwrap();
                let plan = config::preview(&path, |v| install(v, new)).unwrap();
                let changed: Vec<&str> = plan
                    .diff
                    .lines()
                    .filter(|l| !l.starts_with("+++") && !l.starts_with("---"))
                    .filter(|l| l.starts_with('+') || l.starts_with('-'))
                    .collect();
                let ours = a.hook_entries(new).len() + usize::from(a.status_line(new).is_some());
                assert_eq!(changed.len(), 2 * ours, "{kind:?}:\n{}", plan.diff);
                for line in changed {
                    let exe = if line.starts_with('+') { "/new/" } else { "/old/" };
                    assert!(
                        line.contains("\"command\"") && line.contains(exe),
                        "{kind:?}: {line}"
                    );
                }
                // Reinstalling what is there is no change at all.
                config::apply(
                    &path,
                    &plan.fingerprint,
                    |v| install(v, new),
                    std::time::SystemTime::now(),
                )
                .unwrap();
                assert!(config::preview(&path, |v| install(v, new)).unwrap().is_noop());
            }
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The user put another tool's hook in the same group as ours, under a matcher. Update and
    /// Remove touch only our hook there; a group that holds only ours still goes on Remove.
    #[test]
    fn a_group_shared_with_another_tool_keeps_its_hook() {
        use vults_agent_config as config;
        let (old, new) = (Path::new("/old/vults-hook"), Path::new("/new/vults-hook"));
        let dir = std::env::temp_dir().join(format!("vults-agents-shared-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let theirs = serde_json::json!({ "command": "other-tool --check", "timeout": 7, "type": "command" });

        for kind in [AgentKind::Claude, AgentKind::Codex, AgentKind::Gemini] {
            let a = agent(kind).unwrap();
            let event = a.hook_entries(old)[0].event;
            let mut file = config::with_ours(&serde_json::json!({}), &a.hook_entries(old), MARKER);
            let group = &mut file["hooks"][event][0];
            group["matcher"] = "Bash".into();
            group["hooks"].as_array_mut().unwrap().insert(0, theirs.clone());
            let path = dir.join(format!("{kind:?}.json"));
            std::fs::write(&path, serde_json::to_string_pretty(&file).unwrap() + "\n").unwrap();
            let text = std::fs::read_to_string(&path).unwrap();

            // Update: only the lines naming our hook change.
            let install = |v: &Value| config::with_ours(v, &a.hook_entries(new), MARKER);
            let plan = config::preview(&path, install).unwrap();
            let changed: Vec<&str> = plan
                .diff
                .lines()
                .filter(|l| !l.starts_with("+++") && !l.starts_with("---"))
                .filter(|l| l.starts_with('+') || l.starts_with('-'))
                .collect();
            assert_eq!(
                changed.len(),
                2 * a.hook_entries(new).len(),
                "{kind:?}:\n{}",
                plan.diff
            );
            assert!(
                changed.iter().all(|l| l.contains("vults-hook")),
                "{kind:?}:\n{}",
                plan.diff
            );
            let updated = install(&file);
            assert_eq!(updated["hooks"][event][0]["matcher"], "Bash");
            assert_eq!(updated["hooks"][event][0]["hooks"][0], theirs, "{kind:?}");
            assert!(
                config::ours_match(&updated, &a.hook_entries(new), MARKER),
                "{kind:?}"
            );

            // Remove: their hook and its group stay; groups that held only ours go.
            let removed = config::remove_ours(&file, MARKER);
            let mut group = file["hooks"][event][0].clone();
            group["hooks"] = serde_json::json!([theirs]);
            assert_eq!(
                removed,
                serde_json::json!({ "hooks": { event: [group] } }),
                "{kind:?}"
            );
            let plan = config::preview(&path, |v| config::remove_ours(v, MARKER)).unwrap();
            assert!(
                plan.diff
                    .lines()
                    .filter(|l| l.starts_with('+') || l.starts_with('-'))
                    .all(|l| !l.contains("other-tool") && !l.contains("matcher")),
                "{kind:?}:\n{}",
                plan.diff
            );
            config::apply(
                &path,
                &plan.fingerprint,
                |v| config::remove_ours(v, MARKER),
                std::time::SystemTime::now(),
            )
            .unwrap();
            let after = std::fs::read_to_string(&path).unwrap();
            let theirs_text = |t: &str| -> Vec<String> {
                t.lines()
                    .filter(|l| l.contains("other-tool"))
                    .map(str::to_string)
                    .collect()
            };
            assert_eq!(theirs_text(&after), theirs_text(&text), "{kind:?}");
            assert!(!config::has_ours(&serde_json::from_str(&after).unwrap(), MARKER));
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_mcp_tool_is_named_by_its_server() {
        assert_eq!(
            mcp_label("mcp__github__list_prs").as_deref(),
            Some("github · list_prs")
        );
        assert_eq!(mcp_label("mcp__plain"), None);
        assert_eq!(mcp_label("Bash"), None);
    }

    #[test]
    fn a_summary_is_the_first_paragraph_on_one_line() {
        let s = |t: &str| summary_line(t);
        let one = |t: &str| Some(t.to_string());
        assert_eq!(
            s("line one\nline two\nline three"),
            one("line one line two line three")
        );
        assert_eq!(s("**hello** world"), one("hello world"));
        assert_eq!(s("## My Title\nsome text"), one("My Title some text"));
        assert_eq!(s(""), None);
        assert_eq!(s("First para.\n\nSecond para."), one("First para."));
        assert_eq!(
            s("Done. Single commit 450a657 on github-pulse.\n\n---\n\nFiles touched (7)…"),
            one("Done. Single commit 450a657 on github-pulse.")
        );
        assert_eq!(s("Summary line.\n***\nMore details."), one("Summary line."));
        assert_eq!(s("Above.\n___\nBelow."), one("Above."));
        assert_eq!(
            s("Result:\n| Col1 | Col2 |\n|---|---|\n| A | B |"),
            one("Result:")
        );
        assert_eq!(s("- item one\n- item two"), one("item one item two"));
        assert_eq!(s("* first\n* second"), one("first second"));
        assert_eq!(s("• first\n• second"), one("first second"));
        assert_eq!(s("1. step one\n12.  step two"), one("step one step two"));
        assert_eq!(s("\n\nActual content."), one("Actual content."));
        assert_eq!(s("## Summary\n\nIt works.\n\nMore."), one("It works."));
        assert_eq!(s("# Done\n\n---"), one("Done"));
        assert_eq!(
            s("#48 merged, branch deleted.\n\nCI was green."),
            one("#48 merged, branch deleted.")
        );
        assert_eq!(s("#[derive(Debug)]\n\nLater."), one("#[derive(Debug)]"));
        assert_eq!(s("#!/bin/sh\n\nLater."), one("#!/bin/sh"));
        assert_eq!(s("####### Seven\n\nLater."), one("####### Seven"));
    }

    #[test]
    fn a_summary_drops_what_is_only_markup() {
        assert_eq!(summary_line("  \n---\n| a | b |\n****\n**\n``\n#\n"), None);
        assert_eq!(summary_line("**\n\nReal text."), Some("Real text.".into()));
        assert_eq!(
            summary_line("Use `cargo test` and __this__.\r\n\r\nLater."),
            Some("Use cargo test and this.".into())
        );
        // Not lists: no space after the marker, or no number before the dot.
        assert_eq!(
            summary_line("-1 failed, 2.5x faster"),
            Some("-1 failed, 2.5x faster".into())
        );
        assert_eq!(summary_line(". done"), Some(". done".into()));
        // `--` is a dash, not a rule.
        assert_eq!(summary_line("a\n--\nb"), Some("a -- b".into()));
    }

    #[test]
    fn a_summary_is_cut_on_a_char_boundary() {
        assert_eq!(
            summary_line(&"x ".repeat(200)).unwrap().chars().count(),
            SUMMARY_MAX
        );
        let wide = "界".repeat(SUMMARY_MAX + 5);
        let cut = summary_line(&wide).unwrap();
        assert_eq!(cut, format!("{}…", "界".repeat(SUMMARY_MAX)));
        let emoji = format!("{}🦅🦅", "a".repeat(SUMMARY_MAX - 1));
        assert_eq!(
            summary_line(&emoji).unwrap(),
            format!("{}🦅…", "a".repeat(SUMMARY_MAX - 1))
        );
        let lines = format!("{}\n{}\n\nLater.", "a".repeat(150), "b".repeat(100));
        assert_eq!(
            summary_line(&lines).unwrap(),
            format!("{} {}…", "a".repeat(150), "b".repeat(SUMMARY_MAX - 151))
        );
        let exact = "界".repeat(SUMMARY_MAX);
        assert_eq!(summary_line(&exact).unwrap(), exact);
    }

    #[test]
    fn shortening() {
        assert_eq!(shorten("cargo test", 40), "cargo test");
        assert_eq!(shorten("abcdef", 3), "abc…");
        assert_eq!(shorten("first\nsecond", 40), "first…");
        assert_eq!(shorten("ééé", 2), "éé…"); // check-english:allow (multi-byte test input)
        assert_eq!(file_name("/a/b/main.rs"), "main.rs");
        assert_eq!(file_name(r"C:\a\lib.rs"), "lib.rs");
    }
}
